# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs: 
  - job: job1 
    steps:
        - script: echo Hello, world! This is Job1
          displayName: 'Run a one-line script'

        - script: echo Add other tasks to build, test, and deploy your project.
          displayName: 'Run a single-line script'

        - script: echo Another step in the pipeline
          displayName: 'Run an additional script'

  - job: job2
    dependsOn: job1
    steps:
    - script: echo Hello, world! This is Job2
      displayName: 'Run a one-line script'

  - job: job3
    dependsOn: job2
    steps:
    - script: echo Hello, world! This is Job3
      displayName: 'Run a one-line script'

